# Use Node.js LTS
FROM node:18-alpine

WORKDIR /app

# Install deps
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

# Build
RUN npm run build

# Expose port
EXPOSE 8080

# Run Next.js
CMD ["npm", "start"]
